# Loads Dot runtime for a user running the Bash shell, running plugin scripts
# for an "interactive" shell.
#
# Your ~/.bashrc should be a symlink to this file.
#
# Do not make changes to this file -- use Dot plugins!

__file__="$HOME/.bashrc"

if [ ! -L "$__file__" ]; then
  echo "ERROR: $__file__ must be a symlink to lib/shells/bash/bashrc in the Dot framework"
  echo "ERROR: You should not execute or source this script directly!"
  echo "ERROR: Skipping initialization of Dot"
else
  export DOT_FRAMEWORK_DIR="$(cd "$(dirname "$(dirname "$(dirname "$(dirname "$(readlink "$__file__")")")")")" && pwd)"
  export DOT_HOME="$(dirname "$DOT_FRAMEWORK_DIR")"

  export DOT_SHELL=bash
  export DOT_BACKUPS_DIR="$DOT_HOME/.backups"
  export DOT_PLUGINS_DIR="$DOT_HOME/plugins"
  export DOT_PATH_DIR="$DOT_HOME/.path"

  source "$DOT_FRAMEWORK_DIR/lib/shells/bash/load_env"
  source "$DOT_FRAMEWORK_DIR/lib/shells/zsh/prepend_if_missing"

  export PATH="$(prepend_if_missing "$DOT_FRAMEWORK_DIR/libexec" : "$PATH")"
  export PATH="$(prepend_if_missing "$DOT_PATH_DIR"              : "$PATH")"

  # We use globs in many places expecting them to return an empty list rather
  # than fail if no matches are found
  shopt -s nullglob

  # Use cached load order created during installation
  DOT_PLUGINS_DEPENDENCY_ORDER=($(cat "$DOT_HOME/.cache/plugin_load_order"))

  for plugin in ${DOT_PLUGINS_DEPENDENCY_ORDER[@]}; do
    # Define variable so plugin's interactive shell script can use it for convenience
    DOT_PLUGIN_DIR="$DOT_PLUGINS_DIR/$plugin"

    if ! shopt -q login_shell; then
      # Skip if login shell since we already did it in bash_login

      # Load any environment variables defined in `env` directory
      for env_path in "$DOT_PLUGIN_DIR/env/"*; do
        if [ -f "$env_path" ]; then
          if ! load_env "$env_path"; then
            echo "ERROR: Failed to load environment variables for plugin $plugin. Halting"
            exit 1
          fi
        fi
      done
    fi

    # Load any environment variables defined for interactive shells
    for env_path in "$DOT_PLUGIN_DIR/env/interactive/"*; do
      if [ -f "$env_path" ]; then
        if ! load_env "$env_path"; then
          echo "ERROR: Failed to load environment variables $env_path for plugin $plugin. Halting"
          exit 1
        fi
      fi
    done

    for script in "$DOT_PLUGIN_DIR/lib/interactive/"*.bash; do
      if ! source "$script"; then
        echo "ERROR: Problem sourcing interactive script $script for plugin $plugin"
      fi
    done
  done

  if [ -e "$HOME/.bashrc.local" ]; then
    source "$HOME/.bashrc.local"
  fi
fi
