#!/usr/bin/env sh

# Installs a list of Dot plugins in the order specified.

set -o errexit
set -o nounset

. "$DOT_FRAMEWORK_DIR/lib/shells/shared/load_env.sh"

mkdir -p "$DOT_PATH_DIR"

for plugin in "$@"; do
  plugin_dir="$DOT_PLUGINS_DIR/$plugin"

  # Add anything in `libexec` directories to PATH so they can be executed by
  # this plugin or other dependent plugins during install
  for libexec_path in "$plugin_dir/libexec" "$plugin_dir/libexec/setup" "$plugin_dir/libexec/setup/install"; do
    if [ -d "$libexec_path" ]; then
      export PATH="$libexec_path:$PATH"
    fi
  done

  # Load any environment variables defined in relevant `env` directories
  for env_path in "$plugin_dir/env/"* "$plugin_dir/env/setup/"* "$plugin_dir/env/setup/install/"*; do
    if [ -f "$env_path" ]; then
      if ! load_env "$env_path"; then
        echo "ERROR: Failed to load environment variables for plugin $plugin. Halting"
        exit 1
      fi
    fi
  done

  if ! dot::plugin::install "$plugin"; then
    echo "ERROR: Failed to install plugin $plugin. Halting"
    exit 1
  fi
done
