#!/usr/bin/env sh

# Installs a Dot plugin.

set -o errexit
set -o nounset

plugin_name="$1"
export DOT_PLUGIN_DIR="$DOT_PLUGINS_DIR/$plugin_name"

for sub_dir in bin libexec; do
  for bin in "$DOT_PLUGIN_DIR/$sub_dir/"*; do
    if [ ! -d "$bin" ] && [ -x "$bin" ]; then
      ln -fs "$bin" "$DOT_PATH_DIR/$(basename $bin)"
    fi
  done
done

for sub_dir in setup setup/install; do
  for install_script_path in "$DOT_PLUGIN_DIR/$sub_dir/"*; do
    if [ -f "$install_script_path" ]; then

      if [ -x "$install_script_path" ]; then
        "$install_script_path"
      fi

      if [ ! $? -eq 0 ]; then
        echo "ERROR: Problem occurred installing $plugin_name"
        exit 1
      fi
    fi
  done
done
