#!/usr/bin/env sh

# Uninstalls a Dot plugin.

set -o errexit
set -o nounset

plugin_name="$1"
plugin_dir="$DOT_PLUGINS_DIR/$plugin_name"

for sub_dir in setup setup/uninstall; do
  for uninstall_script_path in "$plugin_dir/$sub_dir/"*; do
    if [ -f "$uninstall_script_path" ]; then
      export DOT_PLUGIN_DIR="$plugin_dir"

      if [ -x "$uninstall_script_path" ]; then
        "$uninstall_script_path"
      fi

      if [ ! $? -eq 0 ]; then
        echo "ERROR: Problem occurred uninstalling $plugin_name"
        exit 1
      fi
    fi
  done
done
